Add files via upload
SlavaSTiwari/Programming-Semester-3-2021 pull request #2
Opened 2021-11-20 10:12 UTC by SlavaSTiwari

Lab-1 first draft

2021-11-20 10:19 UTC, SorokinIA commented on sorters.h
> +            seq_B->Delete_first();
Allocation error скорее всего тут

2021-11-20 10:21 UTC, SorokinIA requested changes

2021-11-20 10:21 UTC, SorokinIA commented on dyarray.h
> +class DynamicArray{
нет наследования от Sequence

2021-11-20 10:23 UTC, SorokinIA commented on sequence.h
> +                this->items->Resize(this->items->GetSize()+1);
Функция resize делает копию

2021-11-20 10:29 UTC, DmitryTsikalovsky commented on dyarray.h
> +    void Resize(int new_size){
resize скорее всего Public делать не нужно, он должен быть private и вызываться другими public функциями если надо

2021-11-20 10:30 UTC, DmitryTsikalovsky commented on elem_types.h
> +        //OPERATOR OVERLOADING:
Можно так же добавить оператор [ ] который будет возвращать T&

2021-11-20 10:33 UTC, DmitryTsikalovsky commented on sequence.h
> +        DynamicArray<T> *items;
создается массив dynamicArray?

2021-11-20 10:37 UTC, DmitryTsikalovsky commented on sequence.h
> +
Можно так же переопределить оператор [ ] который будет возвращать T&

2021-11-20 10:40 UTC, DmitryTsikalovsky commented on sorters.h
> +Sequence<T>* bubble_Sort(Sequence<T>* seq, int (*cmp)(T,T)){
int (*cmp)(T,T) нужно сделать int (*cmp)(T&,T&)

2021-11-20 10:40 UTC, DmitryTsikalovsky commented on sorters.h
> +Sequence<T>* bubble_Sort(Sequence<T>* seq, int (*cmp)(T,T)){
и так заменить везде

2021-11-20 10:41 UTC, DmitryTsikalovsky commented on sorters.h
> +/// Bubble Sort:
Можно создать класс Sort например, и там будут находится все сортировки, но это по желанию...

2021-11-20 10:49 UTC, DmitryTsikalovsky commented on sorters.h
> +    Sequence<T>* sorted_seq = seq->GetSubsequence(0, seq->GetLength()-1 );
Происходит копирование данных? Исходные данные которые передавали остаются неотсортированными?
 GetSubsequence вызывает GetSubList на 119 строчке

2021-11-20 10:53 UTC, DmitryTsikalovsky commented on sorters.h
> +
Тут происходит лишнее копирование, точнее вставка
вместо этого можно использовать std:sort()

2021-11-20 10:53 UTC, DmitryTsikalovsky commented on sorters.h
> +            T a = seq->Get(i);
Если переопределить оператор [ ] можно будет его использовать

2021-11-20 10:54 UTC, DmitryTsikalovsky commented on sorters.h
> +            T a = seq->Get(i);
Вместо Get

2021-11-20 10:55 UTC, DmitryTsikalovsky commented on sorters.h
> +                seq->InsertAt(a, i+1);
std:swap() комментарий на 35 строчке

2021-11-20 10:55 UTC, DmitryTsikalovsky commented on sorters.h
> +                seq->InsertAt(b, i);
std:swap() комментарий на 35 строчке

2021-11-20 10:56 UTC, DmitryTsikalovsky commented on sorters.h
> +    seq->InsertAt(a, right);
std:swap() комментарий на 35 строчке

2021-11-20 10:58 UTC, DmitryTsikalovsky commented on sorters.h
> +
Посмотри что такое Move семантика и какое преимущество у него перед копированием

2021-11-20 10:58 UTC, SlavaSTiwari commented on sorters.h
> +
Ты имеешь в виду std::swap()?

2021-11-20 11:00 UTC, DmitryTsikalovsky commented on sorters.h
> +    Sequence<T> *seq_B = seq->GetSubsequence( (n/2), n-1 );
Опять копирование

2021-11-20 11:01 UTC, SlavaSTiwari commented on sorters.h
> +
Я пытался использовать std::swap(), но по какой-то причине это дало странную ошибку, После исследования я не нашел способа использовать std::swap()

2021-11-20 11:02 UTC, SorokinIA commented
Подправить - 
названия классов пишем с большой буквы пример class Student. 
примеры названия методов классов void get_name()

2021-11-20 11:04 UTC, SorokinIA commented on dyarray.h
> +    const T Get(int index){
const T&

2021-11-20 11:04 UTC, DmitryTsikalovsky commented on sequence.h
> +        T Get(int index) const override{
возвращает T&

2021-11-20 11:07 UTC, DmitryTsikalovsky commented on sequence.h
> +
Но это по желанию....

2021-11-20 11:08 UTC, DmitryTsikalovsky commented on sorters.h
> +#ifndef SORTERS_H_INCLUDED
Время засекать нужно отдельно от сортировки, у тебя она находится внутри функции, лучше вынести ее еще выше (засекать время выполнения bubble_Sort а не bSort_util

2021-11-20 11:09 UTC, SorokinIA commented on sorters.h
> +            T b = seq->Get(i+1);
тебе Get вернет копию, введи квадратные скобки [] , которые будут возвращать &

2021-11-20 11:14 UTC, DmitryTsikalovsky commented on dyarray.h
> +        int item_size;
У тебя есть количество элементов, но память может быть выделена под большее количество элементов, чтобы каждый раз не выделять память заново
Есть такое решение: Добавить переменную int capacity например, и в ней будет храниться количество элементов под которую выделена память. При этом нужно поправить append и все функции добавления, а в ресайз записывать количество элементов под которую выделена память

2021-11-27 10:08 UTC, SorokinIA commented on Lab-1/sequence.h
> +            delete items;
???

2021-11-27 10:10 UTC, SorokinIA commented on Lab-1/sequence.h
> +                else{cnt = item_size; }
причесать код бы

2021-11-27 10:13 UTC, SorokinIA commented on Lab-1/sorters.h
> +int compare(const T &a, const T &b)
а почему int?

2021-11-27 10:42 UTC, merged